workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    environment:
      image: ubuntu-latest
      java: 17
    scripts:
      - name: Grant Gradle permissions
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
