workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60
    environment:
      android:
        image: "android:latest"
      vars:
        PACKAGE_NAME: "com.example.myandroidapp" # Change this to your package name
    scripts:
      - name: Set up Gradle
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"

