workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60
    environment:
      image: "ubuntu-latest"
      java: 17
      vars:
        PACKAGE_NAME: "com.example.myandroidapp"  # Replace with your package name
    scripts:
      - name: Set up Gradle permissions
        script: |
          chmod +x ./gradlew
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - "your-email@example.com"  # Replace with your email
